"""View model for tool 1 (Forecast Narrative).

Pure functions over core (forecast, narrative, store) — NO web/Streamlit imports.
Every user-facing string and all formatting that app/ui.py + the page body
produced lives here once, so the FastHTML route renders values verbatim and the
parity gate sees everything. Traceability: docs/migration/forecast_narrative-inventory.md.
"""

from __future__ import annotations

from dataclasses import dataclass

import pandas as pd

from core import forecast, narrative
from core.views import common
from core.views.common import (  # re-exported for the route + tests
    COVERAGE_EMPTY, DERIVED_NOTE, EMPTY_STATE, NO_RISK_FLAGS, PRIOR_NONE_LABEL,
    default_selection, snapshot_options,
)

# --- Tool-1-specific load-bearing strings (ported verbatim — inventory §1b). ---
FOOTER = "Draft — review before submitting. Read-only: nothing is sent anywhere."
# 🟢/🟡/🔴 carry meaning via the adjacent word, not colour alone (a11y).
SECTION_LABELS = {"commit": "🟢 Commit", "upside": "🟡 Upside", "risk": "🔴 Risk"}
SECTIONS = ("commit", "upside", "risk")

__all__ = [  # names the route/tests import off this module
    "COVERAGE_EMPTY", "DERIVED_NOTE", "EMPTY_STATE", "NO_RISK_FLAGS",
    "PRIOR_NONE_LABEL", "FOOTER", "SECTION_LABELS", "SECTIONS",
    "ForecastView", "snapshot_options", "default_selection", "period_for",
    "draft_sections", "metrics_view", "export_markdown", "build",
]


@dataclass(frozen=True)
class ForecastView:
    snapshot_options: list[tuple[int, str]]
    prior_options: list[tuple[int, str]]
    current_id: int
    prior_id: int | None
    quota: float | None
    metrics: dict
    unmatched: dict
    draft: dict
    challenge: dict
    risk: dict
    movement: dict
    period: str


# --- tool-1-specific helpers -------------------------------------------------

def _unmatched(deltas: pd.DataFrame | None) -> dict:
    if deltas is None:
        return {"n": 0, "warning": None}
    n = int((deltas["change_type"] == "unmatched").sum())
    warning = (f"{n} opportunities couldn't be matched to last week — "
               "renamed or ID missing? See the movement table.") if n else None
    return {"n": n, "warning": warning}


def _movement(deltas: pd.DataFrame | None) -> dict:
    if deltas is None or deltas.empty:
        return {"columns": [], "rows": []}
    return {"columns": list(deltas.columns), "rows": common.table_rows(deltas)}


def _challenge(top: pd.DataFrame) -> dict:
    """Largest open deals (the commit/upside deals to pressure-test), with the
    risk-flag names joined — core's forecast.top_deals(flags=...)."""
    if top is None or top.empty:
        return {"columns": [], "rows": []}
    return {"columns": list(top.columns), "rows": common.table_rows(top)}


# --- public API --------------------------------------------------------------

def period_for(current_id: int, db_path=None) -> str:
    """Period label = first token of the snapshot's option label, matching the
    page transform `labels[current_id].split(" ")[0]` (inventory §C-12)."""
    for sid, label in snapshot_options(db_path=db_path):
        if sid == current_id:
            return label.split(" ")[0]
    return ""


def _core_slice(current_id: int, prior_id: int | None, db_path=None):
    rollup = forecast.bucket_rollup(current_id, db_path=db_path)
    prior_rollup = (forecast.bucket_rollup(prior_id, db_path=db_path)
                    if prior_id else None)
    deltas = forecast.wow_delta(current_id, prior_id, db_path=db_path)
    flags = forecast.risk_flags(current_id, db_path=db_path)
    return rollup, prior_rollup, deltas, flags


def draft_sections(current_id: int, prior_id: int | None, quota: float | None,
                   db_path=None) -> dict:
    """The three narrative strings for the given selection — generated by core
    (never restated here). Used to (re)generate the draft region."""
    rollup, prior_rollup, deltas, flags = _core_slice(current_id, prior_id, db_path=db_path)
    return narrative.draft(rollup, deltas, flags, prior_rollup=prior_rollup,
                           quota=quota or None)


def metrics_view(current_id: int, prior_id: int | None, quota: float | None,
                 db_path=None) -> dict:
    """Metrics/coverage panel only — for the quota-scoped partial swap that must
    leave the draft textarea untouched (inventory §C, quota preserves edits)."""
    rollup, prior_rollup, deltas, flags = _core_slice(current_id, prior_id, db_path=db_path)
    return common.metric_block(rollup, prior_rollup, quota, forecast.at_risk_total(flags))


def export_markdown(sections: dict, period: str) -> str:
    """Assemble the .md export from (possibly edited) sections — thin passthrough
    so the route need not import core.narrative directly."""
    return narrative.assemble_markdown(sections, period=period)


def build(current_id: int, prior_id: int | None, quota: float | None,
          db_path=None) -> ForecastView:
    options = snapshot_options(db_path=db_path)
    prior_options = [o for o in options if o[0] != current_id]
    rollup, prior_rollup, deltas, flags = _core_slice(current_id, prior_id, db_path=db_path)
    sections = narrative.draft(rollup, deltas, flags, prior_rollup=prior_rollup,
                               quota=quota or None)
    return ForecastView(
        snapshot_options=options,
        prior_options=prior_options,
        current_id=current_id,
        prior_id=prior_id,
        quota=quota,
        metrics=common.metric_block(rollup, prior_rollup, quota,
                                    forecast.at_risk_total(flags)),
        unmatched=_unmatched(deltas),
        draft=sections,
        challenge=_challenge(forecast.top_deals(current_id, db_path=db_path, flags=flags)),
        risk=common.risk_block(flags),
        movement=_movement(deltas),
        period=period_for(current_id, db_path=db_path),
    )
